apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: my-nginx
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: 'registry.siberyildiz.com/root/deneme_build:master'
        imagePullPolicy: Always
        ports:
        - containerPort: 80

